# Generated by Django 2.0.3 on 2019-01-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
