# Generated by Django 2.0.3 on 2019-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_flight_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='test',
            field=models.IntegerField(null=True),
        ),
    ]
